import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  Menubar,
  MenubarMenu,
  MenubarTrigger,
} from "@/components/ui/menubar"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Aditya Sethi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex justify-center fixed top-10 left-0 w-full">
          <Menubar>
            <MenubarMenu>
              <div className="flex justify-center space-x-4">
              <MenubarTrigger>About</MenubarTrigger>
              <MenubarTrigger>Skills</MenubarTrigger>
              <MenubarTrigger>Projects</MenubarTrigger>
              <MenubarTrigger>Contact</MenubarTrigger>
              </div>
            </MenubarMenu>
          </Menubar>
        </div>
        {children}
      </body>
    </html>
  );
}
