import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  Menubar,
  MenubarMenu,
  MenubarTrigger,
} from "@/components/ui/menubar";
import styles from "./styles.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Aditya Sethi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className={`flex justify-between items-center w-full fixed top-0 ${styles.myDiv}`}>
          <div className="text-2xl font-bold text-white pl-20">
            <a href="#">
              <img src="/skills/typescript.png" className="w-10 h-10" />
            </a>
          </div>

          <Menubar>
            <MenubarMenu>
              <div className="flex space-x-4 ml-auto">
                <MenubarTrigger><a href="#about">About</a></MenubarTrigger>
                <MenubarTrigger><a href="#skills">Skills</a></MenubarTrigger>
                <MenubarTrigger><a href="#projects">Projects</a></MenubarTrigger>
                <MenubarTrigger><a href="#contact">Contact</a></MenubarTrigger>
              </div>
            </MenubarMenu>
          </Menubar>
        </div>
        {children}
      </body>
    </html>
  );
}
